---
title: "Seminar"
author: "Lara"
date: "2023-07-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```
# Packages
```{r }
library(tidyr)
library(tidyverse)
library(stringr)
library(magrittr)
library(ggplot2)
library(readr)
library(readxl)
library(lubridate)
library(dplyr)
library(httr)
library(knitr)
```
# Dataframe:
```{r }
getwd()
mental.health <- read.csv("../Seminar/survey.csv")
str(mental.health)
```
# Cleaning
```{r }
# Age:
# 1st histogram - something weird
mental.health %>% ggplot(aes(x=Age)) + geom_histogram(binwidth = 30, col=1) +
  labs(x = "Idade", y = "Frequencia", title = "Histograma da idade") +
  theme_bw()
# descritive statistics
descritiva <- function(variavel){
  media = mean(variavel)
  sd = sd(variavel)
  maximo = max(variavel)
  minimo = min(variavel)
  variancia = var(variavel)
  cv = (sd/media)*100
  quantis = quantile(variavel)
  
  return(c(média = media, desvio = sd, máximo = maximo, mínimo = minimo, variância = variancia, CV = cv, quartis = quantis))
}
descritiva(mental.health$Age)
#Removing outliers - replacing with mean
mental.health %>% filter(Age < 18 | Age > 90)
mh<-mental.health %>% filter(Age > 17 & Age < 91)
descritiva(mh$Age)
mh %>% ggplot(aes(x=Age)) + geom_histogram(binwidth = 1, col=1) +
  labs(x = "Idade", y = "Frequencia", title = "Histograma da idade") +
  theme_bw()
mental.health$Age <- ifelse(mental.health$Age < 18 | mental.health$Age > 90, 32.076739, mental.health$Age)

descritiva(mental.health$Age)


# Sex:
mental.health$Gender <- mental.health$Gender %>% str_squish() %>% str_to_title() %>% str_remove_all(pattern = "\\-|\\(|\\)|\\/")
table(mental.health$Gender)
mental.health$Gender <- mental.health$Gender %>% str_squish() %>% str_to_title() %>% str_replace_all(pattern = "^.*Trans.*$", replacement = "Transgender")
table(mental.health$Gender)
mental.health$Gender<- mental.health$Gender %>% str_squish() %>% str_to_title() %>% str_replace_all(pattern = "^.*Queer.*$|^.*queer.*$", replacement = "Gender-Queer")
table(mental.health$Gender)
mental.health$Gender <- mental.health$Gender %>% str_squish() %>% str_to_title() %>% str_replace(pattern = "^Female$|^Femail$|^Femake$|^F$|^.*Female.*$|^.*femme.*$", replacement = "Woman")
table(mental.health$Gender)
mental.health$Gender <- mental.health$Gender %>% str_squish() %>% str_to_title() %>% str_replace(pattern = "^Enby$|^Nonbinary$", replacement = "Non-binary")
table(mental.health$Gender)
mental.health$Gender <- mental.health$Gender %>% str_squish() %>% str_to_title() %>% str_replace(pattern = "^Male$|^Mail$|^Make$|^Male$|^Maile$|^M$|^Malr$|^Mal$|^Msle$|^Malr$|^.*Man.*$|^.*Cis.*$", replacement = "Man")
table(mental.health$Gender)
mental.health$Gender <- mental.health$Gender %>% str_squish() %>% str_to_title() %>% str_replace(pattern = "^A Little About You$|^All$|^Guy.*$|^Maleish$|^Nah$|^P$|^Agender$|^Androgyne$|^Neuter$|^.*Male.*$", replacement = "Other")
table(mental.health$Gender)

```

```{r }

```

```{r }

```

```{r }

```

```{r }

```
