---
title: "arquivo"
author: "Lara"
date: "2023-07-04"
output: html_document
---

-----------------------------------------------------------------------------------------------
# ME115
# Classroom R exercises!
## I have made up this data to serve as an example.
-----------------------------------------------------------------------------------------------

# Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)

library(tidyverse)
library(tidyr)
library(dplyr)
library(stringr)
library(ggplot2)
library(magrittr)
library(lubridate)
library(readr)
library(readxl)
library(knitr)
```

# Directory (relative path)
```{r }
getwd()
enem.original<-read_xlsx("../ME115/enem.xlsx", sheet = "Sheet1")
str(enem.original)
head(enem.original, 20)
```

# Data cleaning 
```{r }
# Sexo
table(enem.original$Sexo)
enem.original$Sexo %<>% str_squish() %>% str_to_title() %>% str_replace_all(pattern = "^.*Ale.*$|^Male$|^Masculino$", replacement = "M")
enem.original$Sexo %<>% str_squish() %>% str_to_title() %>% str_replace_all(pattern = "^Female$|^Mulher$", replacement = "F")

# Age
enem.original$DataNasc <- as.character(enem.original$DataNasc)
enem.original$DataNasc <- ymd(enem.original$DataNasc)
```













